### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by Kyved** [google-developer-training/android-basics-kotlin-affirmations-app-solution#1]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards#2

**In which task and step of the codelab can this issue be found?**

In the TextView, set the textAppearance attribute to **?attr/textAppearanceHeadline6.** textAppearance is an attribute that allows you to define text-specific styling. For other possible predefined text appearance values, you can see the TextAppearances section in this blogpost on Common Theme Attributes.

**Describe the problem**

Instead of having : Larger text  I get almost invisible one even if I try with  headline lower than 6 ( 5, 4  etc.)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_
4.0.1

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/68512938/94209492-720b8e00-fe9a-11ea-9af1-f37c7c849956.png)

**Comment by tango4567** [comment]
@Kyved I won't found any issue in this section, even I'm also following step-by-step instructions.

**Comment by jtavva** [comment]
@Kyved, we are not able to reproduce this issue on our end, can you give the emulator version you are using.

**Comment by Kyved** [comment]
Problem solved.

I'm a beginner. I had just forgot to sync changes in Gradle. When done
everything was ok

Thank you

Yves



Le lun. 28 sept. 2020 10 h 13, Tarun Mahajan <notifications@github.com> a
écrit :

**Comment by jtavva** [comment]
@Kyved Glad to hear that!
Thank you for reaching out to us.
