### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by SoulProtagonist** [google-developer-training/android-basics-kotlin-affirmations-app-solution#10]
**url of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards&authuser=1#1

**In which task and step of the codelab can this issue be found?**
"Initialize list of affirmations with images"

**Describe the problem**
missing the line which should be
"Affirmation(R.string.affirmation3, R.drawable.image3)," 
from the code sample, the code has "2" and on the next line "4", missing "3".

**Steps to reproduce?**
1. Go to codelab and read section

**Versions**
4.1.1

**Comment by jtavva** [comment]
@SoulProtagonist 
Thank you so much for reporting this issue. This is fixed and will be published soon.
