### ISSUE TITLE
Android Basics issue: test_solution does not exist in solution 

### ISSUE THREAD

**Issue by alphaunited** [google-developer-training/android-basics-kotlin-affirmations-app-solution#100]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#10

**In which task and step of the codelab can this issue be found?**
Test Lists and Adapters -> Solution code

**Describe the problem**
the code downloaded from GitHub does not contain Test class files
 [android-basics-kotlin-affirmations-app-solution](https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution)

**Steps to reproduce?**
1. Go to... Project files -> Tests
2. Click on...
3. See error... it's empty

**Versions**
_What version of Android Studio are you using?_ 4.1.3

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by axl0d** [comment]
this may help you
#95

**Comment by roro11235** [comment]
Could someone please add the solution to the instrument tests

**Comment by axl0d** [comment]
1. clone the solution repository

```git clone git@github.com:google-developer-training/android-basics-kotlin-affirmations-app-solution.git ```

2. on your terminal or git ui change to the test_solution branch

```git checkout origin/test_solution```

3. you will see the changes applied. 
4. Happy test!
