### ISSUE TITLE
Android Basics: display-list-cards, typo

### ISSUE THREAD

**Issue by skatingtamara** [google-developer-training/android-basics-kotlin-affirmations-app-solution#108]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards&hl=en#2

**In which task and step of the codelab can this issue be found?**
Change the app theme colors > Add color resources > Step 1.

**Describe the problem**
Typo. It says "Open colors.xml (res > color > colors.xml)."

Should say "Open colors.xml (res > **values** > colors.xml)."

**Additional information**

![image](https://user-images.githubusercontent.com/98510821/155771837-7003701a-82b6-4945-ace8-808fdd204486.png)

**Comment by osuleymanova** [comment]
@skatingtamara 
Thank you for reaching out to us. The issue is fixed and the correct path will be published soon:
<img width="1111" alt="Screen Shot 2022-06-07 at 9 58 03 AM" src="https://user-images.githubusercontent.com/86437155/172440104-7debae57-1a99-403c-a9e9-4f7086718a36.png">
