### ISSUE TITLE
Android Basics issue: Dependency for Instrumented Tests

### ISSUE THREAD

**Issue by ninomunoz** [google-developer-training/android-basics-kotlin-affirmations-app-solution#110]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#5

**In which task and step of the codelab can this issue be found?**
Task: Adding instrumentation test dependencies

**Describe the problem**
The code snippet for the androidTest dependency to add is incorrect. It should be
`androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.4.0'`

**Steps to reproduce?**
1. Go to **Adding instrumentation test dependencies**
2. Add Gradle dependency.
3. Instrumentation tests won't compile because support Espresso library is incompatible with androidx RecyclerView.

**Versions**
_What version of Android Studio are you using?_
Android Studio Bumblebee | 2021.1.1 Patch 2

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ninomunoz 
Thank you for reaching out to us. The issue is fixed and published:
![Screen Shot 2022-05-31 at 4 24 16 PM](https://user-images.githubusercontent.com/86437155/171299692-e91d2d32-f7e5-4f18-b433-84ca7c12f606.png)
