### ISSUE TITLE
Android Basics issue: Unusable code not reflected in solution

### ISSUE THREAD

**Issue by forestfish12** [google-developer-training/android-basics-kotlin-affirmations-app-solution#115]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
The issue is found in step 7 of the test lists and adapters codelab

**Describe the problem**
The codelab has you put this code near the end of the task

> ```onView(withId(R.id.recycler_view)).perform(
>    RecyclerViewActions
>        .scrollTo<RecyclerView.ViewHolder>(
>            withText(R.string.affirmation10)
>        )
>    )
>``` 

This is done to enable the code to adapt to the size of a list. In the current setup this code lab has you go through this is broken, giving the error

> androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: an instance of android.widget.TextView and view.getText() equals string from resource id: <2131689500>' on view 'view.getId() is <2131231058/com.example.affirmations:id/recycler_view>'.
> at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
> at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:9)
> at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
> at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
> at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
> at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
> at com.example.affirmations.AffirmationsListTests.scroll_to_item(AffirmationsListTests.kt:21)
> ... 29 trimmed
> Caused by: java.lang.RuntimeException: Found 0 items matching holder with view: an instance of android.widget.TextView and view.getText() equals string from resource id: <2131689500>, but position -1 was requested.
> at androidx.test.espresso.contrib.RecyclerViewActions$ScrollToViewAction.perform(RecyclerViewActions.java:361)
> at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
> at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:22)
> at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
> at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
> at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at android.os.Handler.handleCallback(Handler.java:938)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loopOnce(Looper.java:201)
> at android.os.Looper.loop(Looper.java:288)
> at android.app.ActivityThread.main(ActivityThread.java:7839)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

In the solution code this is final step is not done, leaving the code functional but static.

> ```onView(withId(R.id.recycler_view)).perform(
>    RecyclerViewActions
>        .scrollToPosition<RecyclerView.ViewHolder>(9))
>    )
> ```

If the steps are going to be included then they should leave you with working code and the solution code should reflect this. As of right now the solution code ignores the problem and the codelab doesn't explain that something is broken.

**Steps to reproduce?**
1. Configure the test code for this step as it appears in the codelab.
2. Try to run the test.
3. Test program starts followed by the Affirmations App.
4. Immediate crash when it tries to scroll.

**Versions**
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.blai30.lotus.theme (1.7), com.gmike.visual-studio-2019-dark (1.5.3), com.samdark.intellij-visual-studio-code-dark-plus (2.5), com.vecheslav.darculaDarkerTheme (1.2.0), com.villains.intelij.plugin.trashpandatheme (1.6), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40)

**Additional information**
It initially tells you that you need to disable animations when it crashes but when you disable animations it changes the error to the one listed above.

**Comment by ArixZajicek** [comment]
I've been having the same issue and I thought it was something I was doing wrong, until I cloned the repo and it still did this. It looks like something changed with the espresso contrib library since the tutorial was written, and now this way of running the test doesn't work? I haven't figured it out yet myself.

**Comment by hhyeok1026** [comment]
#107 has the same issue, and there is a solution.

https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/issues/107#issuecomment-1059880096
