### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by Mejihalimelhik** [google-developer-training/android-basics-kotlin-affirmations-app-solution#117]
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters

step 7

this code won't work

onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollTo<RecyclerView.ViewHolder>(
           withText(R.string.affirmation10)
       )
)

unless the textview is accessed by  
hasDescendant(
    withText(R.string.affirmation10)
)

**Comment by asten77** [comment]
Confirmed, I spent a long time trying to figure this out.
