### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by Lasamat** [google-developer-training/android-basics-kotlin-affirmations-app-solution#119]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters&authuser=1#5

**In which task and step of the codelab can this issue be found?**
Task 6

**Describe the problem**

The instructions tell you to add _androidTestImplementation 'com.android.support.test.espresso:espresso-contrib:3.0.2'_ as a dependency but the project did not work that way. The IDE suggested adding _'androidx.test.espresso:espresso-contrib:3.4.0'_

**Steps to reproduce?**
Follow instructions

**Versions**
_What version of Android Studio are you using?_
Bumblebee

**Comment by osuleymanova** [comment]
@Lasamat 
Thank you for reaching out to us. As the content of the codelab is updated not after each release of a version (Kotlin, Gradle, dependencies), so in the future we recommend following the IDEA's auto suggestion to keep the versions  up to date. The current stable version for espresso-contrib is 3.4.0. Happy coding!
