### ISSUE TITLE
Android Basics: recyclerview-scrollable-list

### ISSUE THREAD

**Issue by ffavela** [google-developer-training/android-basics-kotlin-affirmations-app-solution#12]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-recyclerview-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-recyclerview-scrollable-list#1

**In which task and step of the codelab can this issue be found?**

3

**Describe the problem**

Two problems:

1) The version number a bit outdated (not really a problem)
2) It says to replace one line by the next, however when looking at the dependencies it seems that both lines are already there. Doing this means that I should deliberately repeat a line?! 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_
4.1.1

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@ffavela 
Thank you for reaching out to us.
Those instructions as stated are only for Older versions of Android Studio (prior to version 4.1).
If you using latest version of Android Studio (4.1+) you can skip this step. 

![image](https://user-images.githubusercontent.com/24260141/102945227-02457900-4472-11eb-8520-646d9df4a97e.png)
