### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by shalperin** [google-developer-training/android-basics-kotlin-affirmations-app-solution#128]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
7 - Test the recyclerview

**Describe the problem**
Codelab suggests 2 methods for scrolling the recycler view.  The second one (listed below) does not work.

This is the suggested method:
```
onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollTo<RecyclerView.ViewHolder>(  //The codelab suggested we use this alternative method to scroll-to.
           withText(R.string.affirmation10) 
       )
)

onView(withText(R.string.affirmation10))
    .check(matches(isDisplayed())
)

```
Here is the relevant part of the stack trace:
 Error performing 'scroll RecyclerView to: holder with view: an instance of android.widget.TextView and view.getText() equals string from resource id: <2131689499>' on view 'view.getId() is <2131231058/com.samhalperin.android.affirmations:id/recycler_view>'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
...
Caused by: java.lang.RuntimeException: Found 0 items matching holder with view: an instance of android.widget.TextView and view.getText() equals string from resource id: <2131689499>, but position -1 was requested.
at androidx.test.espresso.contrib.RecyclerViewActions$ScrollToViewAction.perform

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by adamg92** [comment]
> Found the solution on another forum but they need to add the fix to the documentation here
> 
> ```
> onView(withId(R.id.recycler_view)).perform(
>    RecyclerViewActions
>        .scrollTo<RecyclerView.ViewHolder>(  
>            hasDescendant(withText(R.string.affirmation10)) // Needs to check the descendants of each view holder 
>        )
> )
> 
> onView(withText(R.string.affirmation10))
>     .check(matches(isDisplayed())
> )
> ```

Ran into this issue today, thank you for the solution. Maybe they will get to updating the docs sometime this year.
