### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by ffavela** [google-developer-training/android-basics-kotlin-affirmations-app-solution#13]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards#2

**In which task and step of the codelab can this issue be found?**
6

**Describe the problem**

After applying the MaterialCardView, the displayed image doesn't correspond to the card version. In fact the same image, the one prior to the change, is displayed twice.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by uzbeki** [comment]
Same with me too. Material Design's Card View does not work (it does not style Linear Layout as proper cards as shown in the tutorial.)

**Comment by jtavva** [comment]
@ffavela 
Thank you for reaching out to us.
The difference is subtle, you need to pay close attention.


![image](https://user-images.githubusercontent.com/24260141/103023706-564c6e00-4503-11eb-8882-b4114e45246f.png)   ![image](https://user-images.githubusercontent.com/24260141/103023738-6401f380-4503-11eb-9f65-f5a5dbb7653c.png)
