### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by hermanngerdes** [google-developer-training/android-basics-kotlin-affirmations-app-solution#132]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
Test Lists and Adapters - Step 7

**Describe the problem**
I do not know, where or how to paste the code provided in Step7 - it always shows errors. In the solution code in step 11 I do not find the file  AffirmationListTests.kt, so I can't look up my mistake.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@hermanngerdes 
Thank you for reaching out to us and sharing your concerns. Hope the screenshot below (with the path and code snippet provided in the step 7 of the codelab) will help you to find the required file:
![Screen Shot 2022-06-07 at 9 30 15 AM](https://user-images.githubusercontent.com/86437155/172434627-fd6fc2c5-2797-4111-b539-867141616293.png)
Happy testing!
