### ISSUE TITLE
Android Basics issue: Tiny documentation change  

### ISSUE THREAD

**Issue by nathansmithbz** [google-developer-training/android-basics-kotlin-affirmations-app-solution#134]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-recyclerview-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-recyclerview-scrollable-list#3)

### **Section in documentation:** Section 4:  Implement onCreateViewHolder()  **-- Step 2** 

Very minor, but I think the word 'inflate' should be formatted as code in step 2 (text for reference)

> Once you have a LayoutInflater object instance, add a period followed by another method call to inflate the actual list item view. Pass in the XML layout resource ID R.layout.list_item and the parent view group. The third boolean argument is attachToRoot. This argument needs to be false, because RecyclerView adds this item to the view hierarchy for you when it's time.

Like this: 
<img width="819" alt="Screenshot 2022-05-27 at 23 38 29" src="https://user-images.githubusercontent.com/79979868/170797479-bc3d6115-cdaf-4718-84b5-5aada4781fd5.png">

Instead of this: 
<img width="827" alt="Screenshot 2022-05-27 at 23 33 28" src="https://user-images.githubusercontent.com/79979868/170797490-d6c2ad27-9735-420c-967e-05195fc9d2f4.png">

**Comment by osuleymanova** [comment]
@nathansmithbz 
Thank you for reaching out to us. The issue is fixed and published:
![Screen Shot 2022-06-07 at 9 19 04 AM](https://user-images.githubusercontent.com/86437155/172431811-2a538022-6e59-4a22-9077-1617291cdfae.png)
