### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by PabloDales** [google-developer-training/android-basics-kotlin-affirmations-app-solution#14]
**URL of codelab**
Hi! This is my first time using Git Hub.
In the course Display a Scrollable List, unit -> Display a list of images using cards, in the section Polishing the UI, the code that goes in the themes/night did not work and made my application crash in the dark mode display of the phone.

**In which task and step of the codelab can this issue be found?**

Display a list of images using cards, in the section Polishing the UI - > Add a resource file for dark theme -> Step 5 (Copy the following into the new themes.xml file (in the values-night directory).

**Describe the problem**

 the next code line made that the application cant be initializated in the dark mode

<item name="android:statusBarColor" tools:targetApi="l">@color/colorPrimaryVariant</item>

i change it for and it worked

<item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@PabloDales 
Thank you so much for reporting this issue. This is fixed in the codelab and will be published soon.
