### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by asaywitz** [google-developer-training/android-basics-kotlin-affirmations-app-solution#142]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
7 Test the RecylerView

**Describe the problem**
Test fails. Missing hasDescendant()

Instead of:

onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollTo<RecyclerView.ViewHolder>(
           withText(R.string.affirmation10)
       )
)

should be

        onView(withId(R.id.recycler_view)).perform(
            RecyclerViewActions
                .scrollTo<RecyclerView.ViewHolder>(
                    hasDescendant(withText(R.string.affirmation10))
                )
        )

See: https://bytemeta.vip/repo/google-developer-training/android-basics-kotlin-affirmations-app-solution/issues/107

**Steps to reproduce?**
1. Run test

**Versions**
_What version of Android Studio are you using?_
Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart (211.7817), io.flutter (67.0.1)

**Additional information**
not needed just run test and it will fail if missing hasDescendant

**Comment by GarleyApps** [comment]
Thank you for sharing the solution
