### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by GarleyApps** [google-developer-training/android-basics-kotlin-affirmations-app-solution#144]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
Step 7 - at the bottom. last sample code:

onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollTo<RecyclerView.ViewHolder>(
           withText(R.string.affirmation10)
       )
)
onView(withText(R.string.affirmation10))
    .check(matches(isDisplayed())
)

**Describe the problem**
when I try to run the "scroll_to_item()" function, I get the error:
androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: an instance of android.widget.TextView and view.getText() equals string from resource id: <2131623964>' on view 'Animations or transitions are enabled on the target device.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_
Android Studio Chipmunk, 2021.2.1 Patch 1

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/107215442/177394413-76983531-566b-4781-bf59-6da3d63acba8.png)

**Comment by peterbucci** [comment]
I think I had the same issue:
https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/issues/146

Included a workaround.

**Comment by GarleyApps** [comment]
I found the solution in issue: #142
