### ISSUE TITLE
Android Basics issue: Step 7 - "Test the Recycler View" example test failing

### ISSUE THREAD

**Issue by peterbucci** [google-developer-training/android-basics-kotlin-affirmations-app-solution#146]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
Step 7 (part 2)

**Describe the problem**
The following snippet:

```kotlin
onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollTo<RecyclerView.ViewHolder>(
           withText(R.string.affirmation10)
       )
)
```

Doesn't pass for the following list item view:
https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/blob/main/app/src/main/res/layout/list_item.xml

This test can pass by modifying to:
```kotlin
onView(withId(R.id.recycler_view)).perform(
    RecyclerViewActions
        .scrollTo<RecyclerView.ViewHolder>(
            hasDescendant(withText(R.string.affirmation10))
        )
)
```

**Steps to reproduce?**
1. Download the project solution from github
2. Include the specific test from the above step (it's not included in the solution by default)
3. Test fails

**Versions**
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64

**Additional information**

**Comment by CloudCodeCraft** [comment]
It looks like this workaround no longer works.

I've cloned the testing solution branch and pasted in this code and I still get errors.

:(

**Comment by ende76** [comment]
You can try something like this:

```kotlin
package com.example.affirmations

import androidx.recyclerview.widget.RecyclerView
import androidx.test.espresso.Espresso.onView
import androidx.test.espresso.assertion.ViewAssertions.matches
import androidx.test.espresso.contrib.RecyclerViewActions
import androidx.test.espresso.matcher.ViewMatchers.*
import androidx.test.ext.junit.rules.ActivityScenarioRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.google.android.material.card.MaterialCardView
import org.hamcrest.Matchers.allOf
import org.hamcrest.Matchers.isA
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented test, which will execute on an Android device.
 *
 * See [testing documentation](http://d.android.com/tools/testing).
 */
@RunWith(AndroidJUnit4::class)
class AffirmationsListTests {
    @get:Rule
    val activity = ActivityScenarioRule(MainActivity::class.java)

    @Test
    fun scroll_to_item() {
        val viewHolder = allOf(
            hasDescendant(withText(R.string.affirmation10)), 
            isA(MaterialCardView::class.java))

        onView(withId(R.id.recycler_view)).perform(
            RecyclerViewActions.scrollTo<RecyclerView.ViewHolder>(
                viewHolder
            )
        )

        onView(viewHolder).check(matches(isDisplayed()))
    }
}
```

**Comment by StephanVanBiljon** [comment]
> It looks like this workaround no longer works.
> 
> I've cloned the testing solution branch and pasted in this code and I still get errors.
> 
> :(

The modification to make the test pass still works:

**Versions**
Android Studio Electric Eel | 2022.1.1 Patch 1
