### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by NaplesDave** [google-developer-training/android-basics-kotlin-affirmations-app-solution#149]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#10

**In which task and step of the codelab can this issue be found?**
11

**Describe the problem**

Solution Code does not contain the files for the TESTS. Or I can't find them in the project. And I couldn't get the code lab to work properly either. An Error with Animations Enabled, and an error with Ordering.Context not working. Very frustrating. I am using Android Emulator for Pixel 3 and Pixel 5 API 31

**Steps to reproduce?**
1. Go to...
2. Click on... Download SOLUTION CODE, look for TESTS in project.
3. See error...

**Versions**
_What version of Android Studio are you using?_
Chipmunk | 2021.2.1 Patch 1

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="471" alt="Screen Shot 2022-07-16 at 10 53 51 PM" src="https://user-images.githubusercontent.com/28597938/179381867-c2729f0c-fa47-4941-9e9a-3c2b1a6141e7.png">

**Comment by Theo-Dancoisne** [comment]
"Solution Code does not contain the files for the TESTS"

agree
