### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by gicanzo** [google-developer-training/android-basics-kotlin-affirmations-app-solution#15]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards#2

**In which task and step of the codelab can this issue be found?**
Task: Display a list of images using cards
Step: 3

**Describe the problem**
In the section "Update dark theme colors", the reader is asked to change the night/themes.xml status bar color by using the following line:

`<item name="android:statusBarColor" tools:targetApi="l">@color/colorPrimaryVariant</item>`

this line however causes an error as the color resource is not found. In the solution file on GitHub, this line is not changed and uses `attr/colorPrimaryVariant`

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
4.1.1 on Ubuntu

**Comment by jtavva** [comment]
@gicanzo 
Thank you so much for reporting this issue. This is fixed in the codelab and will be published soon.
