### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by BB119** [google-developer-training/android-basics-kotlin-affirmations-app-solution#154]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
Step 2

**Describe the problem**
**scrollTo<RecyclerView.ViewHolder>(
           withText(R.string.affirmation10)
       )** causes an error

**Steps to solve it?**
It should be replaced with:
**.scrollTo<RecyclerView.ViewHolder>(
                    hasDescendant(withText(R.string.affirmation10))
                )**

**Versions**
Android Studio Chipmunk 2021.2.1 Patch 2

![Screenshot 2022-08-08 024018](https://user-images.githubusercontent.com/8702105/183322047-a2a6d12e-8153-4aa0-87dd-d5946a04cf18.png)

**Comment by Theo-Dancoisne** [comment]
same problem, i just opened issue with screenshots for more details
https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/issues/155#issue-1335935200
