### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by rafael-perez-dexcom** [google-developer-training/android-basics-kotlin-affirmations-app-solution#166]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
Step 7: Test the RecyclerView. Task number 2.

**Describe the problem**
I found that a piece of code from the code lab does not work for me. This code is failing:
```
onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollTo<RecyclerView.ViewHolder>(
           withText(R.string.affirmation10)
       )
)
```
The xml of the list_item is composed of a MaterialCardview, which has a LinearLayout inside of it, and that linear layout contains an ImageView and a TextView. Seems like Espresso is not able to find the TextView. In order to find the view I had to change the code to use the matcher **hasDescendant**:
```
onView(withId(R.id.recycler_view)).perform(
    RecyclerViewActions
        .scrollTo<RecyclerView.ViewHolder>(
            hasDescendant(
                withText(R.string.affirmation10)
            )
        )
)
```

**Versions**
Android Studio Dolphin | 2021.3.1

**Additional information**
Error screenshot:
![Screen Shot 2022-10-06 at 17 15 32](https://user-images.githubusercontent.com/114116029/194428595-c99db22c-3489-412a-a25f-9e68a24ddab0.png)

**Comment by thechinkysight** [comment]
This can be the possible solution:
https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/issues/107#issuecomment-1059880096
