### ISSUE TITLE
Android Basics issue: Test Lists and Adapters - Step 7.2

### ISSUE THREAD

**Issue by jasonlagaac** [google-developer-training/android-basics-kotlin-affirmations-app-solution#177]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
[Test the RecyclerView](https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6)

**Describe the problem**
Sample code provided breaks the tests:

```
onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollTo<RecyclerView.ViewHolder>(
           withText(R.string.affirmation10)
       )
)
```

Here is a fix:

```
 @Test
    fun scroll_to_item() {
        onView(withId(R.id.recycler_view)).perform(
            RecyclerViewActions
                .scrollTo<RecyclerView.ViewHolder>(
                    hasDescendant(withText(R.string.affirmation10))
                )
        )

        onView(withText(R.string.affirmation10))
            .check(matches(isDisplayed()))
    }
```

**Additional information**

<img width="1552" alt="test-success" src="https://user-images.githubusercontent.com/568204/210173112-56454835-34a0-4c76-ab72-f405bee157f8.png">
<img width="1552" alt="test-fail" src="https://user-images.githubusercontent.com/568204/210173116-ecf9b571-d822-4d01-93ed-e874c11ec673.png">

**Comment by ashirobokov** [comment]
Well... Agreed with you. I didn't see your ticket so did open #180 yesterday. And the solution is to add 'hasDescendant' into block of code. What they need to do is just make a little amendment in the text of this codelab.
