### ISSUE TITLE
Android Basics: recyclerview-scrollable-list

### ISSUE THREAD

**Issue by rm-minus-r-star** [google-developer-training/android-basics-kotlin-affirmations-app-solution#179]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-recyclerview-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-recyclerview-scrollable-list#3

**In which task and step of the codelab can this issue be found?**
step 4

**Describe the problem**
In step 3 the tutorial instructs the user to add 
textView.text = Datasource().loadAffirmations().size.toString()

in MainActivity.kt, but Add a RecyclerView to the layout/Step 4 replaces the textView view, and therefore the app will not compile at Add a RecyclerView to the layout/step 14.

**Steps to reproduce?**
1. Follow instruction in the tutorial.

**Versions**
_What version of Android Studio are you using?_ Android Studio Dolphin | 2021.3.1 Patch 1 Build #AI-213.7172.25.2113.9123335, built on September 30, 2022

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Alionides** [comment]
same problem with me. Build error is :  6 issues were found when checking AAR metadata
