### ISSUE TITLE
Android Basics: recyclerview-scrollable-list

### ISSUE THREAD

**Issue by TheKingsident** [google-developer-training/android-basics-kotlin-affirmations-app-solution#18]
**https://developer.android.com/codelabs/basic-android-kotlin-training-recyclerview-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-recyclerview-scrollable-list#0**

**Use RecyclerView to display a scrollable list >> Before you begin**

**Just a grammatical error**

**Steps to reproduce?**
1. Go to "Use RecyclerView to display a scrollable list"
2. Click on "Before you begin" in the tabs to the left
3. See the error under the heading "What you'll learn"

**Additional information**
The error reads "How to use organize your code into packages" instead of "How to organize your code into packages"

**Comment by jtavva** [comment]
@TheKingsident 
Thank you so much for reporting this issue. This is fixed and will be published soon.
