### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by MattBrooks95** [google-developer-training/android-basics-kotlin-affirmations-app-solution#19]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards#1

**In which task and step of the codelab can this issue be found?**
"Adding images to the list items" step 2

https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/raw/main/images.zip

**Describe the problem**

The zipped folder of example images to be used within the project contained some sort of MacOS hidden folder. It was called "__MACOSX".

**Steps to reproduce?**
1. Download the zipped folder
2. Extract it
3. in addition to the image files there is also some sort of MacOS file.

Obviously not a big deal, and it may not even be worth fixing. I just wanted to let it be known. People may appreciate the only files in the archive being image files.

I don't mean to be a complainer, and I'm grateful for these guides!

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![android_guides_mac_folder](https://user-images.githubusercontent.com/28607360/105621830-17397180-5e4f-11eb-8a39-004ddc53c3a1.png)

**Comment by jtavva** [comment]
@MattBrooks95 
Thank you for reaching out to us.
since this is a not a major blocker, we will leave this as it is for now.
