### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by ezzahmed77** [google-developer-training/android-basics-kotlin-affirmations-app-solution#192]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Issue can be found in TestRecyclerView part 

**Describe the problem**
Must be a hint to stop the animations first when writing the test for recycler view because test fails each time..

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_
Latest one 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jlulovics** [comment]
thank you for your feedback. this content has been deprecated. please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices in Android development.
