### ISSUE TITLE
Android Basics: recyclerview-scrollable-list

### ISSUE THREAD

**Issue by CodeWebWeaver** [google-developer-training/android-basics-kotlin-affirmations-app-solution#193]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-recyclerview-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-recyclerview-scrollable-list#3)

**Adding a RecycleView to your app**

There is a text mistake in "In Android Studio in the Project pane, right-click app > java > com.example.affirmations and select New > Package."

 word with problem:
 "pane"

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jlulovics** [comment]
thank you for your feedback. this content has been deprecated. please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices in Android development.
