### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by richirick** [google-developer-training/android-basics-kotlin-affirmations-app-solution#195]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
There are mistake with "testImplementation("org.mockito:mockito-core:5.8.0")" in https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#8

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#8 
and https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#9
2. See error in file "AffirmationsAdapterTests.kt" in your project.
![mistakeTest](https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/assets/113588596/32050e4d-4ad9-4d0d-8cfc-cd433819512a)

**Versions**
_What version of Android Studio are you using?_
I use Android Studio Giraffe | 2022.3.1
Build #AI-223.8836.35.2231.10406996, built on June 29, 2023

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Possible Solution:
add "debugImplementation("org.mockito:mockito-core:5.8.0")" instead of "testImplementation("org.mockito:mockito-core:5.8.0")"
in build.gradle

**Comment by jlulovics** [comment]
thank you for your feedback. this content has been deprecated. please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices in Android development.
