### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by nicholeb** [google-developer-training/android-basics-kotlin-affirmations-app-solution#3]
https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?

"Use cards" 

I made the changes to add the Material Card View and the app would crash with a logcat error that "The style on this component requires your app theme to be Theme.MaterialComponents" Was on a Nexus 6 emulator. I was able to resolve it by changing the theme. 

**Steps to reproduce?**
Just follow the instructions for adding the card view and run the app. 

**Versions**
_What version of Android Studio are you using?_
4.0.1

**Additional information**
Perhaps I missed an instruction for changing the theme earlier in the codelab, but I went back through it and didn't see anything.

**Comment by jtavva** [comment]
@nicholeb 

Thank you so much for reporting this issue, yes you need to change the parent app theme, if you are in AS 4.0. 
We added a the following note to the code lab and will be published shortly.  

> Note: If you’re using Android Studio 4.0, make this change to your `res > values > styles.xml `file. Change the parent app theme from `Theme.AppCompat.Light.DarkActionBar` to `Theme.MaterialComponents.DayNight.DarkActionBar`.
