### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by mikfas** [google-developer-training/android-basics-kotlin-affirmations-app-solution#33]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Kotlin course - Mutablelist- list of orders

**Describe the problem**
unresolved reference: addItem
unresolved reference: addItem

**Steps to reproduce?**
1. Go to...
...continues
val order4 = Order(4).addItem(Noodles()).**_addItem_**(Vegetables("Cabbage", "Onion"))
ordersList.add(order4)
ordersList.add(

Order(5)
     .addItem(Noodles())
     .**_addItem_**(Noodles())
     .addItem(Vegetables("Spinach")))
    
    for (order in ordersList) {
        order.print()
        println()
    }
}

2. Click on...
3. See error...
the item in BOLD (addItem) get red and it appears this messages
Unresolved reference: addItem
Unresolved reference: addItem

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@mikfas 
Thank you for reaching out to us. The snippet of your code is totally correct. 
I suggest to double check this part of your code:

 class Order(val orderNumber: Int) {
    private val itemList = mutableListOf<Item>()

    fun addItem(newItem: Item)  : Order   {
        itemList.add(newItem)
        return this
    }

Probably you missed :Order and return this

If it doesn't help please share with us the snippet of the whole code not just the fragment.
