### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by PsyYak** [google-developer-training/android-basics-kotlin-affirmations-app-solution#36]
https://developer.android.com/codelabs/basic-android-kotlin-training-lists?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#7

Step 8, at code section

Wrap the while / loop declaration into an actual code block to display it

![image](https://user-images.githubusercontent.com/65914952/117569718-ba955600-b0cf-11eb-9bfa-ca9d977f13fb.png)

**Comment by osuleymanova** [comment]
@PsyYak 
Thank you for reaching out to us. The issue is fixed and will be published soon.
