### ISSUE TITLE
Android Basics: lists: shorthand for in-place division is /= instead of \=

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-affirmations-app-solution#38]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-lists

**In which task and step of the codelab can this issue be found?**
4. Loop Through a List

**Describe the problem**
There is a note:

> Note: Because doing a simple operation on a variable and storing it back in the variable is common, there is a shorthand for it using the += operator. There are equivalent operators for minus (-=) , multiplication (*=) and division (\=). See more details here.

However, the division part is wrong. It should be `/=` instead of `\=`.

**Comment by osuleymanova** [comment]
@johnlinp 
Thank you for reporting this issue. It is fixed and published.
