### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by lsperling** [google-developer-training/android-basics-kotlin-affirmations-app-solution#4]
[https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-display-list-cards#2](url)

**first issue**
styling the textView inside the list_item.xml

when I added the styling line:
`android:textAppearance="?attr/textAppearanceHeadline6"`
the text appeared small and not at all styled the wanted way.
I had to "Invalidate caches / restart" in order to get the style working.

**second issue**
use cards

when I added the card view and tried to run, my app crashed. I've ran debug with the logcat and saw:
`Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).`

then, with the help of stackoverflow, i've added the following line to the materialcardview xml:
`android:theme="@style/Theme.MaterialComponents.Light"`
and then my app worked and looked as it should.

my android studio version: 4.0.1

**Comment by jtavva** [comment]
@lsperling 
Thank you so much for reporting this issue, yes you need to change the parent app theme, if you are in AS 4.0. 
We added a the following note to the code lab and will be published shortly.  

> Note: If you’re using Android Studio 4.0, make this change to your `res > values > styles.xml `file. Change the parent app theme from `Theme.AppCompat.Light.DarkActionBar` to `Theme.MaterialComponents.DayNight.DarkActionBar`.
