### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-affirmations-app-solution#41]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-lists#3

**In which task and step of the codelab can this issue be found?**
While loops

**Describe the problem**
In the sentence in a Note: "There are equivalent operators for minus (-=) , multiplication (*=) and division (\=)." it seems that the "\=" should be "/=".

**Steps to reproduce?**
As stated above.

**Versions**
Not applicable.

**Additional information**
Nil.

**Comment by osuleymanova** [comment]
@KKH-tw 
Thank you for reporting this issue. It is fixed and will be published soon.
