### ISSUE TITLE
Android Basics: display-list-cards

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-affirmations-app-solution#44]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards#2

**In which task and step of the codelab can this issue be found?**
Change the app icon

**Describe the problem**
In the sentence "If your browser shows the file instead of downloading it, select FIle > Save Page As... to save it to your computer." the "i" in "FIle" seems to have been falsely capitalized.

**Steps to reproduce?**
As stated above.

**Versions**
Not applicable.

**Additional information**
Nil.

**Comment by osuleymanova** [comment]
@KKH-tw 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-display-list-cards#2
