### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by ericcanton** [google-developer-training/android-basics-kotlin-affirmations-app-solution#45]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-lists?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#3

**In which task and step of the codelab can this issue be found?**
"Use Lists in Kotlin" Step 8, the green boxed note about augmented assignment operators.

**Describe the problem**
***(Typo)*** The division assignment operator is written in the box as \\=. This should be /=.
If you [follow the link](https://kotlinlang.org/docs/reference/operator-overloading.html#assignments) to see more details, the operator is correct on that page.

**Steps to reproduce?**
This is just a typo, leaving these blank.
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ericcanton** [comment]
It seems this is already an issue, https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/issues/41

Closing.

**Comment by ericcanton** [comment]
Sorry, re-opening. That issue is slightly different, though it's still about a typo in the division assignment operator.

**Comment by osuleymanova** [comment]
@ericcanton 
thank you for reaching out to us. The issue will be fixed and published soon.
