### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by Bhasura88** [google-developer-training/android-basics-kotlin-affirmations-app-solution#49]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

https://developer.android.com/codelabs/basic-android-kotlin-training-lists?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#4

**Describe the problem**

in the Kotlin playground the results were not displayed

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/88440708/128186882-f89b63ca-3d1e-42f7-837a-097e22038cf2.png)

**Comment by osuleymanova** [comment]
@Bhasura88 
Thank you for reaching out to us. Your code is almost correct, just above the line open class Item... you need to remove fun main() { , then override fun toString for class Vegetables, and remove the curly bracket at the end. The solution code should look like this:

open class Item(val name: String, val price: Int)
    
    class Noodles : Item("Noodles", 10) {
        override fun toString(): String {
            return name
        }
    }
    
    class Vegetables : Item("Vegetables", 5) {
       override fun toString(): String {
            return name
        }
    }
    
    fun main() {
        val noodles = Noodles()
        val vegetables = Vegetables()
        println(noodles)
        println(vegetables)
    }
