### ISSUE TITLE
Android Basics: lists incorrect immutable list for val moreItems

### ISSUE THREAD

**Issue by jtonic** [google-developer-training/android-basics-kotlin-affirmations-app-solution#5]
https://developer.android.com/codelabs/basic-android-kotlin-training-lists?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#2 

_3. Introduction to Mutable Lists. section 4. Create a list of moreItems. You won't have to change it, so make it a val and immutable._

In this codelab step it is about the kotlin mutable list and moreItems has to be a mutableListOf("ravioli", "lasagna", "fettuccine").
In the example the type of the moreItems is incorrect (it is immutable list),
val moreItems = listOf("ravioli", "lasagna", "fettuccine")

**Comment by jtavva** [comment]
@jtonic 
Thank you for reaching out to us.
In the task **Introduction to Mutable Lists ->Create a MutableList**
You will create `entrees`  as a Mutable Lists. 
In the later part of the task you will create a immutable list also, that is `moreitems`.
