### ISSUE TITLE
Android Basics: recyclerview-scrollable-list

### ISSUE THREAD

**Issue by Abdallah54321** [google-developer-training/android-basics-kotlin-affirmations-app-solution#51]
https://developer.android.com/codelabs/basic-android-kotlin-training-recyclerview-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-recyclerview-scrollable-list&hl=en#4

file ItemAdapter.kt

Tried copying all the code into android studio and still not getting compiled due to an error on line 44 stringResourceId

holder.textView.text = context.resources.getString(item.stringResourceId)

Running 2020.3.1 latest android studio. July 26 build. on Apple Mac M1

Suspect thecodelab text needs updating as some of the instructions did not get the expected outcome during code lab.

**Comment by Germanicus1982** [comment]
To anyone reading this for the solution change...

`holder.textView.text = context.resources.getString(item.stringResourceId)`

to

`holder.textView.text = context.resources.getString(item.stringResourceId.toInt())`
