### ISSUE TITLE
Android Basics: recyclerview-scrollable-list

### ISSUE THREAD

**Issue by mehulpatel510** [google-developer-training/android-basics-kotlin-affirmations-app-solution#69]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Content not display properly in install android developers home screen 

**Steps to reproduce?**
1. https://developer.android.com/
2. View android courses
3. New! Android Basics in Kotlin -> start course
4. Unit 2: Layouts -> explore
5. Display a scrollable list -> explore
6. Use RecyclerView to display a scrollable list -> take codelab

**Versions**
_What version of Android Studio are you using?_
Android 10

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![Uploading Screenshot_20211107-084013.png…]()

**Comment by osuleymanova** [comment]
@mehulpatel510 
Thank you for reaching out to us. Could you please clarify the issues you faced with? Some screenshots could help a lot.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no user's response back.
Please create a new one, if you need help.
All the best learning Android.
