### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by gszesiek** [google-developer-training/android-basics-kotlin-affirmations-app-solution#7]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-lists?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#4

**In which task and step of the codelab can this issue be found?**
Vegetables(listOf("cabbage", "sprouts", "onion"))**)**

**Describe the problem**
Nothing spectacular but it should be:
Vegetables(listOf("cabbage", "sprouts", "onion"))

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
