### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by mijo1989** [google-developer-training/android-basics-kotlin-affirmations-app-solution#73]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@mijo1989 
The issue is closed as no further clarification of it was provided.
