### ISSUE TITLE
Android Basics issue: Test codelab's code doesn't work

### ISSUE THREAD

**Issue by angelomarzocchi** [google-developer-training/android-basics-kotlin-affirmations-app-solution#74]
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#5

I found a problem in the Test Lists and Adapter Codelab,in 6th and 7th point.

6th point:
There is a dependecy needed (androidx.multidex:multidex:2.0.1) but it's not mentioned. I had to find out the hard way.

7th point:
The test actually doesn't work. For some reason the app can't run on test (It can run as normal app) and the problem seems to be that "Activity never becomes requested state".

I just followed what the Codelab told me to do.

Android Studio Arctic Fox | 2020.3.1 Patch 4
Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64

**Comment by shining-armour** [comment]
Hey, I'm also greeted with the same error that "Activity never becomes requested state". Did you manage to solve it?
