### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by hanzhere** [google-developer-training/android-basics-kotlin-affirmations-app-solution#8]
https://developer.android.com/codelabs/basic-android-kotlin-training-lists?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#4

```
Vegetables(listOf("cabbage", "sprouts", "onion")))
```
There is a residual parentheses at the end of the line of code above
It should be 
```
Vegetables(listOf("cabbage", "sprouts", "onion"))
```

**Comment by jtavva** [comment]
@hanzhere 
Thank you so much for reporting this issue. This is fixed and will be published soon.
