### ISSUE TITLE
Android Basics issue: Extra bracket

### ISSUE THREAD

**Issue by Weaam87** [google-developer-training/android-basics-kotlin-affirmations-app-solution#87]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
onView(withId(R.id.recycler_view)).perform(
   RecyclerViewActions
       .scrollToPosition<RecyclerView.ViewHolder>(9))
)

**Describe the problem**
There is an extra bracket at the end of the code

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by aredshaw** [comment]
+1 I found the same issue.

**Comment by osuleymanova** [comment]
@Weaam87, @aredshaw 
Thank you for reaching out to us. The typo is fixed and published:


![Screen Shot 2022-06-24 at 2 21 39 PM](https://user-images.githubusercontent.com/86437155/175685096-84992d1d-5313-4d33-a4e8-2e957b80a554.png)
