### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by gtblack4** [google-developer-training/android-basics-kotlin-affirmations-app-solution#88]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6

**In which task and step of the codelab can this issue be found?**
7. Test the RecyclerView
Step 2

**Describe the problem**

When using the following code to check whether the text on the screen matches what text is supposed to be displayed I received an error: 
Code used:
onView(withText(R.string.affirmation10))
    .check(matches(isDisplayed()))
Error:
e: C:\Users\$myusername\Downloads\android-basics-kotlin-affirmations-app-solution-main\android-basics-kotlin-affirmations-app-solution-main\app\src\androidTest\java\AffirmationsListTests.kt: (30, 20): Type mismatch: inferred type is Boolean but ViewAssertion! was expected

Instead I had to use the following code in order to complete the task
 onView(withText(R.string.affirmation10))
            .check(ViewAssertions.matches(isDisplayed()))

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_
202.3.1 Patch 4

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Error Code
![image](https://user-images.githubusercontent.com/17162911/148703223-16810d0f-1fed-4d2f-9095-1e61caa06716.png)
Working Code
![image](https://user-images.githubusercontent.com/17162911/148703209-9f28440d-3398-4cac-ae21-f332459c5519.png)

**Comment by osuleymanova** [comment]
@gtblack4 
Thank you for reaching out to us and providing the screenshot of the error.
 I would suggest to replace 'import androidx.test.espresso.assertion.ViewAssertions' with 'import androidx.test.espresso.assertion.ViewAssertions.matches' and try to run the code. 
Please check the screenshot below: 
![Screen Shot 2022-06-01 at 10 13 08 AM](https://user-images.githubusercontent.com/86437155/171462640-4acf001e-6907-439f-a89f-8b7aadaec605.png)
Happy coding!
