### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by themohal** [google-developer-training/android-basics-kotlin-affirmations-app-solution#9]
**URL of codelab**
https://codelabs.developers.google.com/codelabs/basic-android-kotlin-training-lists?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fcodelabs.developers.google.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#1

**In which task and step of the codelab can this issue be found?**
listOf(1, 2, 3, 4, 5, 6) returns a red-only list of integers from 1 through 6.

**Describe the problem**
Type at returns a red-only list its read-only

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_What version of Android Studio are you using?_

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@themohal 
Thank you so much for reporting this issue. This is fixed and will be published soon.
